/*
 * This source file was generated by the Gradle 'init' task
 */
package org.javafxCloudGallery.utilities;

import org.mindrot.jbcrypt.BCrypt;

public class PasswordUtil {
    public static String hashPassword(String plainPassword) {
        return BCrypt.hashpw(plainPassword, BCrypt.gensalt());
    }

    public static Boolean verifyPassword(String hashed, String plain) {
        return BCrypt.checkpw(plain, hashed);
    }
}
